In [1]:
import numpy as np
import pandas as pd
from NeuralNetwork import loss, activation, layer, network
import plotly.graph_objects as go
import plotly.express as px

In [35]:
weights = np.random.randn(250, 10000)
weights

array([[-0.52881931, -0.88407359, -2.24538334, ...,  0.01075017,
        -0.41616578,  0.24796037],
       [ 0.10284859,  0.8822701 ,  0.49693139, ..., -1.13261322,
        -0.42265771, -0.2092144 ],
       [ 0.68929161, -0.26386644,  0.2762624 , ...,  1.61023318,
         0.93216965, -0.50822526],
       ...,
       [ 2.05688512,  1.67288699,  2.57711436, ..., -0.8362772 ,
        -0.048402  , -0.27227775],
       [-2.74126616, -1.00324408,  1.47363857, ..., -2.43546356,
        -0.46459531, -1.93199903],
       [ 0.55301346, -0.30117293,  1.14437919, ...,  0.71313471,
        -0.57057905, -0.82621537]])

In [36]:
weights.mean(axis=1)

array([-2.02698442e-02,  5.58977307e-03, -1.16807082e-02, -5.68409302e-03,
       -8.06089738e-03, -5.27522914e-04, -9.16661471e-04,  1.43006209e-02,
        2.21746532e-03,  5.14911598e-03,  5.77685559e-03, -6.45200326e-03,
        1.73449838e-02, -6.69665405e-03, -1.44629736e-03,  1.16405148e-02,
       -1.25453539e-02,  8.19239747e-03,  1.45663410e-03, -5.34329732e-03,
        1.56444753e-02, -9.05196920e-03, -5.52710085e-03, -6.62572727e-03,
       -4.55223281e-03,  1.02662025e-02,  5.81799006e-04, -1.00583015e-02,
       -5.69060726e-03, -7.46750366e-03, -7.50949408e-03,  1.95401070e-03,
        7.95359159e-03, -1.07979812e-02, -8.03595660e-03,  3.64682456e-03,
       -1.51850398e-02,  1.58102497e-03, -3.94284287e-03,  1.26713455e-02,
       -1.58947374e-02, -1.60409099e-02,  5.86715382e-03, -1.47700096e-02,
       -1.27369261e-02, -1.32296232e-02, -1.49516623e-02, -5.32288342e-03,
        9.98726843e-03, -7.40498507e-03, -9.68729008e-03,  9.14492129e-03,
       -2.14435658e-02, -

In [54]:
weights.var(axis=1)

array([1.01964705, 0.98270191, 1.00655417, 0.99579894, 0.99648385,
       1.01420519, 1.02345937, 0.99724839, 1.00513   , 1.00355516,
       0.99215595, 1.00525929, 0.9923381 , 1.00851076, 1.02830676,
       0.98998919, 1.00546357, 1.01636768, 1.01121691, 1.00911221,
       0.99043671, 1.03451988, 0.99609126, 1.00706663, 0.9827596 ,
       0.99136842, 1.00559006, 0.98536427, 0.98107142, 0.99733334,
       0.99816264, 0.97756983, 0.99807175, 1.01379839, 1.00479316,
       0.99400246, 1.00846205, 0.9879811 , 0.99233798, 1.00466379,
       1.00987433, 1.00805166, 1.01448033, 1.00532115, 0.98519064,
       1.01345333, 1.00108991, 1.01136679, 0.9915659 , 1.00043081,
       1.01160247, 0.979764  , 1.01113046, 0.99942877, 1.01684027,
       1.00435746, 0.97942883, 1.00301932, 1.01924681, 1.01999085,
       0.9925215 , 0.99849436, 1.00239104, 0.99226148, 1.01971226,
       1.00871339, 0.99550104, 1.00154589, 0.99940149, 1.02184699,
       0.992538  , 0.97535321, 0.99937463, 0.96935877, 1.01905

In [52]:
weights.sum(axis=1).std()

93.3172503455215

# XOR Gate Prediction

In [ ]:
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

Y = np.array([[0], [1],
              [1], [0]])

In [ ]:
model = network.Sequential()
model.add_layer(layer.Dense(n_neurons=3, name='Layer_1', freeze_weights=False, weights=np.array([[0.1, 0.2, 0.3],
                                                                                                     [0.6, 0.4, 0.7]]),
                                bias=np.array([[0, 0, 0]])))

model.add_layer(activation.Sigmoid(name='Activation_1'))

model.add_layer(layer.Dense(n_neurons=1, name='Layer_2', freeze_weights=False, weights=np.array([[0.1],
                                                                                                     [0.4],
                                                                                                     [0.9]]),
                                bias = np.array([[0]])))

model.add_layer(activation.Sigmoid(name='Activation_2'))

print(model)
model.compile(loss=loss.MSE(), inputs=X, target=Y, batch=4)
print(model)

model.train(epochs=5000)

pred_val = model.predict(inputs=X)
print(pred_val)

# Quantile Regression Prediction Interval
Prediction Interval at 0.977 - 0.023 ~ 0.95

In [ ]:
def f_predictable(x):
    return x+np.sin(np.pi*x/2)


def f(x, std=0.2):
    return f_predictable(x)+np.random.randn(len(x))*std


def get_data(num, start=0, end=4):
        x = np.sort(np.random.rand(num)*(end-start)+start)
        y = f(x)
        return x.reshape(-1, 1), y

x_train, y_train = get_data(num=20000)
y_train = y_train.reshape(-1,1)
x_test, y_test = get_data(num=1000)
y_test = y_test.reshape(-1,1)

In [ ]:
model_upper = network.Sequential()

model_upper.add_layer(layer.Dense(n_neurons=100, name='Layer_1', freeze_weights=False, lr=0.01))

model_upper.add_layer(activation.ReLU(name='Activation_1'))

model_upper.add_layer(layer.Dense(n_neurons=100, name='Layer_2', freeze_weights=False, lr=0.01))

model_upper.add_layer(activation.ReLU(name='Activation_2'))

model_upper.add_layer(layer.Dense(n_neurons=100, name='Layer_3', freeze_weights=False, lr=0.01))

model_upper.add_layer(activation.ReLU(name='Activation_3'))

model_upper.add_layer(layer.Dense(n_neurons=1, name='Layer_4', freeze_weights=False, lr=0.01))

model_upper.compile(loss=loss.Quantile(quantile=0.977), inputs=x_train, target=y_train, batch=24)

model_upper.train(epochs=400)

In [ ]:
model_lower = network.Sequential()

model_lower.add_layer(layer.Dense(n_neurons=100, name='Layer_1', freeze_weights=False, lr=0.01))

model_lower.add_layer(activation.ReLU(name='Activation_1'))

model_lower.add_layer(layer.Dense(n_neurons=100, name='Layer_2', freeze_weights=False, lr=0.01))

model_lower.add_layer(activation.ReLU(name='Activation_2'))

model_lower.add_layer(layer.Dense(n_neurons=100, name='Layer_3', freeze_weights=False, lr=0.01))

model_lower.add_layer(activation.ReLU(name='Activation_3'))

model_lower.add_layer(layer.Dense(n_neurons=1, name='Layer_4', freeze_weights=False, lr=0.01))

model_lower.compile(loss=loss.Quantile(quantile=0.023), inputs=x_train, target=y_train, batch=24)

model_lower.train(epochs=400)

In [ ]:
fig = go.Figure()

fig.add_trace(go.Scatter(x=x_train.reshape(-1), y=y_train.reshape(-1),
                    mode='markers',
                    name='Original Data'))

fig.add_trace(go.Scatter(x=x_test.reshape(-1), y=model_upper.predict(x_test).reshape(-1),
                    mode='lines',
                    name='Upper Bound'))

fig.add_trace(go.Scatter(x=x_test.reshape(-1), y=model_lower.predict(x_test).reshape(-1),
                    mode='lines',
                    name='Lower Bound'))


fig.show()

# Image Classification
Multi Class Prediction

In [ ]:
np.random.seed(42)

cat_images = np.random.randn(700, 2) + np.array([0, -3])
mouse_images = np.random.randn(700, 2) + np.array([3, 3])
dog_images = np.random.randn(700, 2) + np.array([-3, 3])

feature_set = np.vstack([cat_images, mouse_images, dog_images])
labels = np.array([0]*700 + [1]*700 + [2]*700)

one_hot_labels = np.zeros((2100, 3))

for i in range(2100):
    one_hot_labels[i, labels[i]] = 1
    
dataset = pd.DataFrame(np.hstack([feature_set, labels.reshape(-1, 1)]), columns=['X','Y','Labels'])
dataset.Labels = dataset.Labels.astype('str')

In [ ]:
fig = px.scatter(dataset, x="X", y="Y", color="Labels", hover_data=[dataset.index])
fig.update_layout(width=1000, height=800)
fig.show()

Using Cross Entropy

In [ ]:
model = network.Sequential()

model.add_layer(layer.Dense(n_neurons=4, name='Layer_1', freeze_weights=False, lr=0.001))

model.add_layer(activation.Sigmoid(name='Activation_1'))

model.add_layer(layer.Dense(n_neurons=3, name='Layer_2', freeze_weights=False, lr=0.001))

model.add_layer(activation.Sigmoid(name='Activation_2'))

model.compile(loss=loss.CrossEntropy(), inputs=feature_set, target=one_hot_labels, batch=16)

model.train(epochs=1000)

In [ ]:
pred_val = np.argmax(model.predict(feature_set), axis=1)
np.where((pred_val == labels)==False)

Using SquaredHinge

In [ ]:
one_hot_labels = -1*np.ones((2100, 3))

for i in range(2100):
    one_hot_labels[i, labels[i]] = 1

In [ ]:
model = network.Sequential()

model.add_layer(layer.Dense(n_neurons=4, name='Layer_1', freeze_weights=False, lr=0.001))

model.add_layer(activation.Sigmoid(name='Activation_1'))

model.add_layer(layer.Dense(n_neurons=3, name='Layer_2', freeze_weights=False, lr=0.001))

model.add_layer(activation.Tanh(name='Activation_2'))

model.compile(loss=loss.SquaredHinge(), inputs=feature_set, target=one_hot_labels, batch=16)

model.train(epochs=1000)

In [ ]:
pred_val = np.argmax(model.predict(feature_set), axis=1)
np.where((pred_val == labels)==False)

# Image Classification
Multi Label Prediction

In [ ]:
np.random.seed(42)

cat_images = np.random.randn(700, 2) + np.array([0, -3])
mouse_images = np.random.randn(700, 2) + np.array([3, 3])
dog_images = np.random.randn(700, 2) + np.array([-3, 3])

feature_set = np.vstack([cat_images, mouse_images, dog_images])
labels = np.array([0]*700 + [1]*700 + [1]*700)

one_hot_labels = np.zeros((2100, 3))

for i in range(700):
    one_hot_labels[i, labels[i]] = 1
    
for i in range(700, 2100):
    one_hot_labels[i,1:] = 1
    
dataset = pd.DataFrame(np.hstack([feature_set, labels.reshape(-1, 1)]), columns=['X','Y','Labels'])
dataset.Labels = dataset.Labels.astype('str')

In [ ]:
fig = px.scatter(dataset, x="X", y="Y", color="Labels", hover_data=[dataset.index])
fig.update_layout(width=1000, height=800)
fig.show()

Using Cross Entropy

In [ ]:
model = network.Sequential()

model.add_layer(layer.Dense(n_neurons=4, name='Layer_1', freeze_weights=False, lr=0.001))

model.add_layer(activation.Sigmoid(name='Activation_1'))

model.add_layer(layer.Dense(n_neurons=3, name='Layer_2', freeze_weights=False, lr=0.001))

model.add_layer(activation.Sigmoid(name='Activation_2'))

model.compile(loss=loss.CrossEntropy(), inputs=feature_set, target=one_hot_labels, batch=16)

model.train(epochs=1000)

In [ ]:
pred_val = np.where(model.predict(feature_set)>0.5, 1, 0)
np.where((pred_val == one_hot_labels)==False)

Using SquaredHinge

In [ ]:
one_hot_labels = -np.ones((2100, 3))

for i in range(700):
    one_hot_labels[i, labels[i]] = 1
    
for i in range(700, 2100):
    one_hot_labels[i,1:] = 1

In [ ]:
model = network.Sequential()

model.add_layer(layer.Dense(n_neurons=4, name='Layer_1', freeze_weights=False, lr=0.001))

model.add_layer(activation.Sigmoid(name='Activation_1'))

model.add_layer(layer.Dense(n_neurons=3, name='Layer_2', freeze_weights=False, lr=0.001))

model.add_layer(activation.Tanh(name='Activation_2'))

model.compile(loss=loss.SquaredHinge(), inputs=feature_set, target=one_hot_labels, batch=16)

model.train(epochs=1000)

In [ ]:
pred_val = np.where(model.predict(feature_set)>0, 1, -1)
np.where((pred_val == one_hot_labels)==False)